logo: Fox Noises # add logo name
title: Fox Noises
description: > # this means to ignore newlines until "baseurl:"
  Vulkan Graphics Programming, procedural generation, large-scale rendering,
  and space stuff!
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fuchstraumer.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: Fox Noises
banner-desc: Graphics Programming, Procedural Generation, Music, and Space Stuff

# Author settings
author-pic: avatar.jpg # your photo
author-name: fuchstraumer # your name
email: fuchstraumer@gmail.com # your email

github: fuchstraumer
soundcloud: nofuchsgiven
youtube: channel/UCy6OfyozylFV_n5BkWaS90A
linkedin: keegan-jones-a5ab7a119

# Disqus
discus_identifier: fuchstraumer # add your discus identifier

# Tracker
analytics: UA-30324363-1 

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, .bundle, src, vendor, CNAME, LICENSE, Rakefile, old]
