
title: Fox Noises
email: fuchstraumer@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Graphics Programming and Space Stuff
footer-links:
  github: fuchstraumer
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://fuchstraumer.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
# fixed flags
version: v1.2.0
kramdown:
  input: GFM
  synatx_highlighter: rouge
  syntax_highliger_opts:
    css_class: 'highlight'
  
sass:
  style: :expanded

theme: minima
plugins:
  - jekyll-feed
  - jekyll-mentions

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
